Feature: add packages file
fishtown-analytics/taboola pull request #2
Opened 2019-01-02 18:41 UTC by axelazaid

* added `packages.yml` file and installed `dbt-utils`
* updated existing models

2019-01-08 20:52 UTC, drewbanin commented on packages.yml
> + - package: fishtown-analytics/dbt_utils
:+1:

2019-01-09 14:32 UTC, jthandy requested changes

2019-01-09 14:32 UTC, jthandy commented on packages.yml
> +   version: '>=0.1.20'
I don't think we need this version number to be quite so high, right? When did these two functions exist? I feel like it was many version ago...

2019-01-10 16:18 UTC, jthandy approved these changes

2019-01-10 16:24 UTC, merged